name: Build and Deploy to Github Pages
'on':
  - push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout \U0001F6CE️"
        uses: actions/checkout@v2.3.1
      - name: "Deploy \U0001F680"
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public